project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - installation.qmd
    - apashiny.qmd
    - options.qmd
    - writing.qmd
    - thesis-tutorial.qmd
    - resources.qmd
    - changelog.qmd

website:
  title: "apaquarto"
  navbar:
    left:
      - text: Intro
        href: index.qmd
      - text: Install
        href: installation.qmd
      - text: App
        href: apashiny.qmd
      - text: Options
        href: options.qmd
      - text: APA Markdown
        href: writing.qmd       
      - text: Thesis Tutorial
        href: thesis-tutorial.qmd
      - resources.qmd
      - changelog.qmd
    right: 
      - icon: github
        href: https://github.com/wjschne/apaquarto
        text: Source

bibliography: bibliography.bib

knitr: true

format:
  html:
    theme: 
      - spacelab
      - apaquarto.scss
    tbl-cap-location: top
    toc: true
    toc-location: left


execute:
  freeze: auto
