---
title: "Template Options"
toc: true
editor:
  markdown: 
    canonical: true
---

Options are set in the metadata section at the top of the .qmd file. Quarto metadata uses [YAML](https://yaml.org/), a format that allows us to store data in a format that is easy to write and easy to read. In its simplest form, it has a key and a value:

``` yaml
key: value
```

If the value is simple, it does not need any quotes. If it has any characters that have special meaning in yaml (e.g., `:`), you will need to put the value in quotes.

``` yaml
title: "This title needs quotes: Because there is a colon in it."
```

Any optional key you do not use can be deleted or commented out. If you would prefer to keep the key visible but empty, you can make the value `NULL` with the tilde symbol `~` like so:

``` yaml
key: ~
```

Here is a minimal example of what the YAML metadata might look like:

``` yaml
---
title: "My Paper's Title: A Full Analysis of Everything"
shorttitle: "My Paper's Title"
author:
  - name: W. Joel Schneider
    corresponding: true
    orcid: 0000-0002-8393-5316
    email: schneider@temple.edu
    affiliations:
      - name: Temple University
        department: College of Education and Human Development
        address: 358 Ritter Hall
        city: Philadelphia
        region: PA
        postal-code: 19122-6091
abstract: "This is my abstract."
keywords: [keyword1, keyword2]
author-note:
  disclosures:
    conflict of interest: The author has no conflict of interest to declare.
bibliography: mybibfile.bib     
format:
  apaquarto-docx: default
  apaquarto-html: default
  apaquarto-pdf: default
  apaquarto-typst: default
---
```

# General Options

+------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Field                        | Explanation                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
+:=============================+:=======================================================================================================================================================================================================================================================================================================================================================================================================================================================================+
| `title`                      | Sets the title.                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                              | Titles with no special characters can be raw text.                                                                                                                                                                                                                                                                                                                                                                                                                     |
|                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                              | ``` yaml                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                              | title: My title                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                              | ```                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
|                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                              | If your title has a colon in it, it will need to be quoted:                                                                                                                                                                                                                                                                                                                                                                                                            |
|                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                              | ``` yaml                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                              | title: "My Title: My Subtitle"                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|                              | ```                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
|                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                              | You can list your title and subtitle separately, and they will be combined with a colon in the document:                                                                                                                                                                                                                                                                                                                                                               |
|                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                              | ``` yaml                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                              | title: My Title                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                              | subtitle: My Subtitle                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
|                              | ```                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
+------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `shorttitle`                 | A short version of the title that appears in the running header for .pdf and .docx formats. If omitted or null (`~`), the running header will take its value from the `title` field (and will omit the `subtitle`).                                                                                                                                                                                                                                                    |
+------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `abstract`                   | The abstract paragraph.                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                              | If the abstract is a single paragraph, put it on a single line like most of the other fields:                                                                                                                                                                                                                                                                                                                                                                          |
|                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                              | ``` yaml                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                              | abstract: This is a single-paragraph abstract.                                                                                                                                                                                                                                                                                                                                                                                                                         |
|                              | ```                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
|                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                              | If the abstract has multiple paragraphs, separate them like so:                                                                                                                                                                                                                                                                                                                                                                                                        |
|                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                              | ``` yaml                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                              | abstract: |                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
|                              |   | This is the first paragraph.                                                                                                                                                                                                                                                                                                                                                                                                                                       |
|                              |   | This is the second paragraph.                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                              |   | This the third paragraph.                                                                                                                                                                                                                                                                                                                                                                                                                                          |
|                              | ```                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
+------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `keywords`                   | A list of topics your paper relates to. Can be single words or short phrases. There are two ways to format key words.                                                                                                                                                                                                                                                                                                                                                  |
|                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                              | Comma-separated list with square brackets:                                                                                                                                                                                                                                                                                                                                                                                                                             |
|                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                              | ``` yaml                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                              | keywords: [First keyword, Second keyword, Third keyword]                                                                                                                                                                                                                                                                                                                                                                                                               |
|                              | ```                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
|                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                              | Multiline list with indented hyphens :                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                              | ``` yaml                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                              | keywords:                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
|                              |   - First keyword                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                              |   - Second keyword                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|                              |   - Third keyword                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                              | ```                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
+------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `floatsintext`               | Specifies where floats (i.e., figures and tables) appear.                                                                                                                                                                                                                                                                                                                                                                                                              |
|                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                              | -   If `true`, figures and tables will be intermingled in text.                                                                                                                                                                                                                                                                                                                                                                                                        |
|                              | -   If `false`, figures and tables will appear at the end of the document.                                                                                                                                                                                                                                                                                                                                                                                             |
|                              | -   If omitted, defaults to `false`.                                                                                                                                                                                                                                                                                                                                                                                                                                   |
|                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                              | The `floatsintext` field does not apply when a .pdf output is in journal mode.                                                                                                                                                                                                                                                                                                                                                                                         |
+------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `numbered-lines`             | Numbered lines (.pdf and .docx only)                                                                                                                                                                                                                                                                                                                                                                                                                                   |
|                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                              | Default: `false`                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
+------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `bibliography`               | File(s) with references.                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                              | If you have a single file, you can list it like so:                                                                                                                                                                                                                                                                                                                                                                                                                    |
|                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                              | ``` yaml                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                              | bibliography: mybibliography.bib                                                                                                                                                                                                                                                                                                                                                                                                                                       |
|                              | ```                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
|                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                              | If you have multiple files, you can make an array:                                                                                                                                                                                                                                                                                                                                                                                                                     |
|                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                              | ``` yaml                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                              | bibliography: [mybibliography.bib, myotherbibliography.bib]                                                                                                                                                                                                                                                                                                                                                                                                            |
|                              | ```                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
+------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `mask`                       | For anonymous peer review, removes identifying information: author names, author affiliations, author notes, correspondence information, and references listed in the `masked-citations` field.                                                                                                                                                                                                                                                                        |
|                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                              | If `true`, identifying information is removed.                                                                                                                                                                                                                                                                                                                                                                                                                         |
|                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                              | If `false` or omitted, all information is left as is.                                                                                                                                                                                                                                                                                                                                                                                                                  |
+------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `masked-citations`           | A list of citation keys that should be masked if the `mask` field is `true`. For example:                                                                                                                                                                                                                                                                                                                                                                              |
|                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                              | ``` yaml                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                              | mask: true                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
|                              | masked-citations:                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                              |   - mypublication2020                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
|                              |   - mypublication2024                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
|                              | ```                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
|                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                              | The citation keys should be as they appear in the bibliography file(s).                                                                                                                                                                                                                                                                                                                                                                                                |
+------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `suppress-title-page`        | Suppress the title page if `true`                                                                                                                                                                                                                                                                                                                                                                                                                                      |
+------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `meta-analysis`              | By default, all studies listed in the `nocite` field will be marked with asterisks in the References section. If this behavior is unwanted, set `meta-analysis` to false.                                                                                                                                                                                                                                                                                              |
+------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `no-ampersand-parenthetical` | APA style uses ampersands in parenthetical citations (e.g., Schneider & McGrew, 2018) but not in narrative (i.e., in-text) citations: Schneider and McGrew (2018). You can replace ampersands with "and" in parenthetical citations (e.g., Schneider and McGrew, 2018) by setting the `no-ampersand-parenthetical` option to `true`. A different replacement word other than "and" can be set in the `citation-last-author-separator` field in the `language` options. |
+------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `impact-statement`           | A paragraph below the Abstract that describes the theoretical/practical importance of the work. The heading of the impact statement is "Impact Statement" by default but can be overridden using the `title-impact-statement` field in the `language` field.                                                                                                                                                                                                           |
+------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: {.primary tbl-colwidths="\[25,75\]"}

## Authors

The apaquarto uses the [standard Quarto schema for authors](https://quarto.org/docs/authoring/front-matter.html#author). It has a lot of options, some of which are not needed for the apaquarto extension (e.g., `fax`).

The `author` field contains author names, author affiliations, and author roles. Where possible, specify each author's [orcid](https://orcid.org/) for easy, unambiguous identification.

The corresponding author is specified by setting the author's corresponding field to true (i.e., `corresponding: true`). This author needs to list an email and list a mailing address in the affiliation data. Only one author can be the corresponding author. Other authors do not need to list their addresses.

``` yaml
author:
  - name: W. Joel Schneider
    corresponding: true
    orcid: 0000-0002-8393-5316
    email: schneider@temple.edu
    affiliations:
      - name: Temple University
        department: College of Education and Human Development
        address: 1301 Cecil B. Moore Ave.
        city: Philadelphia
        region: PA
        postal-code: 19122-6091
    role:
      - writing
      - conceptualization
  - name: Fulano Zutano Mengano
    affiliations: Universidad de Dondequiera
    orcid: 0000-0000-0000-0001
    role:
      - formal anlaysis
      - visualization
      - editin
  - name: Thomas Richard Harris
    affiliations: 
      - name: Generic State University
        department: Department of Scholarly Studies
    orcid: 0000-0000-0000-0002
    role:
      - editing
      - funding acquistion
  - name: Wut C. Whosis
    affiliations: Whatchama College
    orcid: 0000-0000-0000-0003
    role:
      - software
      - methodology
      - editing
```

## Affiliations

The apaquarto extenstion uses the [standard Quarto schema for affiliations](https://quarto.org/docs/journals/authors.html#affiliations-schema).

+---------------+---------------------------------------------------------------------------------------------------------------------------+
| Field         | Explanation                                                                                                               |
+===============+===========================================================================================================================+
| `id`          | A unique identifier for the affiliation. The `id` can be useful for specifying an affiliation shared by multiple authors: |
|               |                                                                                                                           |
|               | ``` yaml                                                                                                                  |
|               | author:                                                                                                                   |
|               |   - name: William Joel Schneider                                                                                          |
|               |     affiliations:                                                                                                         |
|               |       - name: Temple University                                                                                           |
|               |         department: College of Education and Human Development                                                            |
|               |         address: 1301 Cecil B. Moore Ave.                                                                                 |
|               |         city: Philadelphia                                                                                                |
|               |         region: PA                                                                                                        |
|               |         postal-code: 19122-6091                                                                                           |
|               |         id: temple                                                                                                        |
|               |   - name: Rene M. Tobin                                                                                                  |
|               |     affiliations:                                                                                                         |
|               |       - ref: temple                                                                                                       |
|               | ```                                                                                                                       |
+---------------+---------------------------------------------------------------------------------------------------------------------------+
| `name`        | The name of the organization.                                                                                             |
|               |                                                                                                                           |
|               | ``` yaml                                                                                                                  |
|               | author:                                                                                                                   |
|               |   - name: Fred Jones                                                                                                      |
|               |     affiliation:                                                                                                          |
|               |       - name: Generic State Univeristy                                                                                    |
|               | ```                                                                                                                       |
|               |                                                                                                                           |
|               | If the author is unaffiliated, list the author's city and region/state instead:                                           |
|               |                                                                                                                           |
|               | ``` yaml                                                                                                                  |
|               | author:                                                                                                                   |
|               |   - name: Fred Jones                                                                                                      |
|               |     affiliation:                                                                                                          |
|               |       - city: San Francisco                                                                                               |
|               |         region: CA                                                                                                        |
|               | ```                                                                                                                       |
+---------------+---------------------------------------------------------------------------------------------------------------------------+
| `department`  | A specific division within the organization.                                                                              |
+---------------+---------------------------------------------------------------------------------------------------------------------------+
| `group`       | A subdivision within the department                                                                                       |
|               |                                                                                                                           |
|               | ``` yaml                                                                                                                  |
|               | author:                                                                                                                   |
|               |   - name: Fred Jones                                                                                                      |
|               |     affiliation:                                                                                                          |
|               |       - name: Generic State Univeristy                                                                                    |
|               |         department: Department of Psychology                                                                              |
|               |         group: Counseling Psychology                                                                                      |
|               | ```                                                                                                                       |
+---------------+---------------------------------------------------------------------------------------------------------------------------+
| `address`     | The street address                                                                                                        |
+---------------+---------------------------------------------------------------------------------------------------------------------------+
| `city`        | City                                                                                                                      |
+---------------+---------------------------------------------------------------------------------------------------------------------------+
| `region`      | The region, state, or province.                                                                                           |
|               |                                                                                                                           |
|               | You may specify `state` instead, if you prefer.                                                                           |
+---------------+---------------------------------------------------------------------------------------------------------------------------+
| `country`     | Country                                                                                                                   |
+---------------+---------------------------------------------------------------------------------------------------------------------------+
| `postal-code` | Postal code (zip code in the U.S.)                                                                                        |
+---------------+---------------------------------------------------------------------------------------------------------------------------+

: {.primary tbl-colwidths="\[25,75\]"}

### Multiple Affiliations

If an author has more than one affiliation:

``` yaml
author:
  - name: William Joel Schneider
    affiliations:
      - name: Temple University
        department: College of Education and Human Development
        address: 1301 Cecil B. Moore Ave.
        city: Philadelphia
        region: PA
        postal-code: 19122-6091
      - name: My Second Affiliation
```

### Shared Affiliations

If two authors have the same affiliation, you can type the same affiliation twice. If you do this, make sure the affiliations are EXACTLY the same in every detail. Otherwise they will be listed as different. To make sure they are listed as the same affiliation, it is safer to use a reference id to make sure that there are no accidental differences that creep in to the editing process. In this example, the affiliation information was entered once, and the `id` was specified. For the second author with the same affiliation, the `ref` field is used to reference the previously specified `id`.

``` yaml
author:
  - name: William Joel Schneider
    affiliations:
      - name: Temple University
        department: College of Education and Human Development
        address: 1301 Cecil B. Moore Ave.
        city: Philadelphia
        region: PA
        postal-code: 19122-6091
        id: temple
  - name: Rene M. Tobin
    affiliations:
      - ref: temple
```

### Listing Authors and Affiliations Separately

If there are a lot of authors with shared affiliations, it might be easier to list the affiliations separately and specify each affiliation's `id`, which can be looked up with the `ref` field:

``` yaml
author: 
  - name: Fred Jones
    affiliation: 
      - ref: temple
      - ref: tamu
  - name: Wanda James
    affiliation:
      - ref: temple
      - ref: ucb
affiliations:
  - id: temple
    name: Temple University
  - id: tamu
    name: "Texas A&M University"
  - id: ucb
    name: University of California, Berkeley
```

## Author Roles

APA Style encourages but does not require papers with multiple authors to describe author roles using the [Contributor Roles Taxonomy](https://credit.niso.org/) (CRediT). There are 14 contributor roles:

+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Role                                                                                          | Description                                                                                                                                                                                                     |
+===============================================================================================+=================================================================================================================================================================================================================+
| [`conceptualization`](https://credit.niso.org/contributor-roles/conceptualization/)           | Ideas; formulation or evolution of overarching research goals and aims.                                                                                                                                         |
+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [`data curation`](https://credit.niso.org/contributor-roles/data-curation/)                   | Management activities to annotate (produce metadata), scrub data and maintain research data (including software code, where it is necessary for interpreting the data itself) for initial use and later re-use. |
+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [`formal analysis`](https://credit.niso.org/contributor-roles/formal-analysis/)               | Application of statistical, mathematical, computational, or other formal techniques to analyse or synthesize study data.                                                                                        |
+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [`funding acquisition`](https://credit.niso.org/contributor-roles/funding-acquisition/)       | Acquisition of the financial support for the project leading to this publication.                                                                                                                               |
+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [`investigation`](https://credit.niso.org/contributor-roles/investigation/)                   | Conducting a research and investigation process, specifically performing the experiments, or data/evidence collection.                                                                                          |
+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [`methodology`](https://credit.niso.org/contributor-roles/methodology/)                       | Development or design of methodology; creation of models.                                                                                                                                                       |
+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [`project administration`](https://credit.niso.org/contributor-roles/project-administration/) | Management and coordination responsibility for the research activity planning and execution.                                                                                                                    |
+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [`resources`](https://credit.niso.org/contributor-roles/resources/)                           | Provision of study materials, reagents, materials, patients, laboratory samples, animals, instrumentation, computing resources, or other analysis tools.                                                        |
+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [`software`](https://credit.niso.org/contributor-roles/software/)                             | Programming, software development; designing computer programs; implementation of the computer code and supporting algorithms; testing of existing code components.                                             |
+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [`supervision`](https://credit.niso.org/contributor-roles/supervision/)                       | Oversight and leadership responsibility for the research activity planning and execution, including mentorship external to the core team.                                                                       |
+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [`validation`](https://credit.niso.org/contributor-roles/validation/)                         | Verification, whether as a part of the activity or separate, of the overall replication/reproducibility of results/experiments and other research outputs.                                                      |
+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [`visualization`](https://credit.niso.org/contributor-roles/visualization/)                   | Preparation, creation and/or presentation of the published work, specifically visualization/data presentation.                                                                                                  |
+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [`writing`](https://credit.niso.org/contributor-roles/writing-original-draft/)                | Preparation, creation and/or presentation of the published work, specifically writing the initial draft (including substantive translation).                                                                    |
+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [`editing`](https://credit.niso.org/contributor-roles/writing-review-editing/)                | reparation, creation and/or presentation of the published work by those from the original research group, specifically critical review, commentary or revision -- including pre- or post-publication stages.    |
+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: {.primary tbl-colwidths="\[25,75\]"}

It is possible to list the roles for each author:

``` yaml
author: 
  - name: Fred Jones
    role: 
      - conceptualization
      - funding acquisition
      - writing
  - name: Wanda James
    role:
      - conceptualization
      - formal analysis
      - visualization
      - editing
```

When 2 or more authors have the same role, one may specify the degree of contribution (`lead`, `equal`, `supporting`):

``` yaml
author: 
  - name: Fred Jones
    role: 
      - conceptualization: lead
      - visualization: supporting
      - investigation: equal
      - funding acquisition
      - writing
  - name: Wanda James
    role:
      - conceptualization: supporting
      - visualization: lead
      - investigation: equal
      - formal analysis
      - editing
```

## Author Notes

The first paragraph of the Author Note will be populated with all the ORCID IDs that have been specified.

The second paragraph consists of status changes:

+----------------------+-----------------------------------------------------------------------+
| Field                | Explanation                                                           |
+======================+=======================================================================+
| `affiliation-change` | Describe author affiliation changes.                                  |
|                      |                                                                       |
|                      | Example:                                                              |
|                      |                                                                       |
|                      | ``` yaml                                                              |
|                      | author-note:                                                          |
|                      |   status-changes:                                                     |
|                      |     affiliation-change: Fred Jones is now at Generic State University |
|                      | ```                                                                   |
+----------------------+-----------------------------------------------------------------------+
| `deceased`           | Disclose names of authors who are now deceased.                       |
|                      |                                                                       |
|                      | Example:                                                              |
|                      |                                                                       |
|                      | ``` yaml                                                              |
|                      | author-note:                                                          |
|                      |   status-changes:                                                     |
|                      |     deceased: Fred Jones is deceased.                                 |
|                      | ```                                                                   |
+----------------------+-----------------------------------------------------------------------+

: {.primary tbl-colwidths="\[25,75\]"}

The third paragraph consists of study details and author disclosures:

+-------------------------+----------------------------------------------------------------------------------------------------------------------------------+
| Field                   | Explanation                                                                                                                      |
+=========================+==================================================================================================================================+
| `study-registration`    | Describe where the study was registered.                                                                                         |
|                         |                                                                                                                                  |
|                         | Example:                                                                                                                         |
|                         |                                                                                                                                  |
|                         | ``` yaml                                                                                                                         |
|                         | author-note:                                                                                                                     |
|                         |   disclosures:                                                                                                                   |
|                         |     study-registration: "This study was registered at ClinicalTrials.gov (Identifier NTC998877)."                                |
|                         | ```                                                                                                                              |
+-------------------------+----------------------------------------------------------------------------------------------------------------------------------+
| `data-sharing`          | Data/materials that have been shared                                                                                             |
|                         |                                                                                                                                  |
|                         | Example:                                                                                                                         |
|                         |                                                                                                                                  |
|                         | ``` yaml                                                                                                                         |
|                         | author-note:                                                                                                                     |
|                         |   disclosures:                                                                                                                   |
|                         |     data-sharing: "Data from this study can be accessed at https://academicdata.org/jones2024."                                  |
|                         | ```                                                                                                                              |
+-------------------------+----------------------------------------------------------------------------------------------------------------------------------+
| `related-report`        | Acknowledge and cite data/materials that were used previously                                                                    |
|                         |                                                                                                                                  |
|                         | Example:                                                                                                                         |
|                         |                                                                                                                                  |
|                         | ``` yaml                                                                                                                         |
|                         | author-note:                                                                                                                     |
|                         |   disclosures:                                                                                                                   |
|                         |     related-report: "This article is based on the dissertation completed by Graham (2018)"                                       |
|                         | ```                                                                                                                              |
+-------------------------+----------------------------------------------------------------------------------------------------------------------------------+
| `conflict-of-interest`  | Disclose author conflicts of interest                                                                                            |
|                         |                                                                                                                                  |
|                         | Example:                                                                                                                         |
|                         |                                                                                                                                  |
|                         | ``` yaml                                                                                                                         |
|                         | author-note:                                                                                                                     |
|                         |   disclosures:                                                                                                                   |
|                         |     conflict-of-interest: "Fred Jones has been a paid consultant for Corporation X, which funded this study."                    |
|                         | ```                                                                                                                              |
+-------------------------+----------------------------------------------------------------------------------------------------------------------------------+
| `financial-support`     | Acknowledge funding sources                                                                                                      |
|                         |                                                                                                                                  |
|                         | Example:                                                                                                                         |
|                         |                                                                                                                                  |
|                         | ``` yaml                                                                                                                         |
|                         | author-note:                                                                                                                     |
|                         |   disclosures:                                                                                                                   |
|                         |     financial-support: "This study was supported by Grant 123 from Academic Funders United."                                     |
|                         | ```                                                                                                                              |
+-------------------------+----------------------------------------------------------------------------------------------------------------------------------+
| `gratitude`             | Authors can express gratitude.                                                                                                   |
|                         |                                                                                                                                  |
|                         | Example:                                                                                                                         |
|                         |                                                                                                                                  |
|                         | ``` yaml                                                                                                                         |
|                         | author-note:                                                                                                                     |
|                         |   disclosures:                                                                                                                   |
|                         |     gratitude: "The authors are grateful to Sidney Fiero for thoughtful comments on an early draft of this paper."               |
|                         | ```                                                                                                                              |
+-------------------------+----------------------------------------------------------------------------------------------------------------------------------+
| `authorship-agreements` | Authors can disclose any agreements they entered into regarding the paper.                                                       |
|                         |                                                                                                                                  |
|                         | Example:                                                                                                                         |
|                         |                                                                                                                                  |
|                         | ``` yaml                                                                                                                         |
|                         | author-note:                                                                                                                     |
|                         |   disclosures:                                                                                                                   |
|                         |     authorship-agreements: "Because the authors are equal contributors, order of authorship was determined by a fair coin toss." |
|                         | ```                                                                                                                              |
+-------------------------+----------------------------------------------------------------------------------------------------------------------------------+

: {.primary tbl-colwidths="\[25,75\]"}

The fourth paragraph of the Author Note consists of the correspondence information. It will created automatically from the contact information from the author marked as the corresponding author. If you wish to override this paragraph with one entirely of your own, you can set it via the `correspondence-note` subfield in the `author-note` field.

``` yaml
author-note:
  correspondence-note: This will override the correspondence note that would otherwise be generated.
```

# Options for .docx and typst

+---------------------------------+-----------------------------------------------------------------------------------------------------------------------------------+
| Field                           | Explanation                                                                                                                       |
+:================================+:==================================================================================================================================+
| `blank-lines-above-title`       | Number of blank lines above the title.                                                                                            |
|                                 |                                                                                                                                   |
|                                 | If omitted, defaults to 2 double-spaced lines.                                                                                    |
|                                 |                                                                                                                                   |
|                                 | APA style requests that you put your title 3 to 4 lines (i.e., 1.5 to 2 double-spaced lines) down from the top of the title page. |
+---------------------------------+-----------------------------------------------------------------------------------------------------------------------------------+
| `blank-lines-above-author-note` | Number of double-spaced lines between author affiliations and author note.                                                        |
|                                 |                                                                                                                                   |
|                                 | APA style wants the note to start around the middle of the page. You can play with the number. It defaults to 2 if omitted.       |
+---------------------------------+-----------------------------------------------------------------------------------------------------------------------------------+

: {.primary tbl-colwidths="\[25,75\]"}

# Options for .pdf

All of the .pdf-specfic options for apaquarto come directly from the [apa7 $\LaTeX$ package](https://ctan.org/pkg/apa7?lang=en). Consult the apa7 package documentation for greater detail.

+--------------------+-------------------------------------------------------------------------------+
| Field              | Explanation                                                                   |
+====================+===============================================================================+
| `documentmode`     | Alter the overall style of the document. Options incluce:                     |
|                    |                                                                               |
|                    | -   `man` Manuscript: Similar to .docx format                                 |
|                    | -   `jou` Journal: A polished two-column format similar to many APA journals. |
|                    | -   `doc` Document: Similar to default $\LaTeX$ articles.                     |
|                    | -   `stu` Student: Formatted for student papers                               |
+--------------------+-------------------------------------------------------------------------------+
| `course`           | Fields that are used only for student papers (`stu` mode).                    |
|                    |                                                                               |
| `professor`        | Example:                                                                      |
|                    |                                                                               |
| `duedate`          | ``` yaml                                                                      |
|                    | course: Introduction to Statistics (EDUC 5101)                                |
|                    | professor: W. Joel Schneider                                                  |
|                    | duedate: 12/22/2024                                                           |
|                    | ```                                                                           |
+--------------------+-------------------------------------------------------------------------------+
| `journal`          | Fields that are used only for Journal (`jou`) mode.                           |
|                    |                                                                               |
| `volume`           | Example:                                                                      |
|                    |                                                                               |
| `copyrightnotice`  | ``` yaml                                                                      |
|                    | journal: Psychological Review                                                 |
| `copyrightext`     | volume: 2024, Vol. 131, No. 2, 10--60                                         |
|                    | copyrightnotice: 2024                                                         |
|                    | copyrightext: All rights reserved                                             |
|                    | ```                                                                           |
+--------------------+-------------------------------------------------------------------------------+
| `fontsize`         | Size of font.                                                                 |
|                    |                                                                               |
|                    | Options include `10pt`, `11pt`, and `12pt`                                    |
+--------------------+-------------------------------------------------------------------------------+
| `a4paper`          | If `true`, uses a4 paper size instead of 8.5 by 11 in. letter size.           |
+--------------------+-------------------------------------------------------------------------------+
| `donotrepeattitle` | If `true`, suppresses title in the first page of text.                        |
+--------------------+-------------------------------------------------------------------------------+
| `draftfirst`       | If `true`, puts draft watermark on first page.                                |
+--------------------+-------------------------------------------------------------------------------+
| `draftall`         | If `true`, puts draft watermark on all pages.                                 |
+--------------------+-------------------------------------------------------------------------------+
| `nocorrespondence` | If `true`, hides correspondence text                                          |
+--------------------+-------------------------------------------------------------------------------+

: {.primary tbl-colwidths="\[25,75\]"}

# Options for .html

With one exeception, everything that works for .docx should work for .html. For .html, there is no benefit to having line numbers in the text because the text wrapping differs depending on the device and size of the window the document is being viewed.

# Suppress Elements

Any of the elements below can be selectively suppressed from the document.

+--------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Field                                      | Explanation                                                                                                                                                                                |
+============================================+============================================================================================================================================================================================+
| `suppress-title-page: true`                | Suppress the entire title page                                                                                                                                                             |
+--------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `suppress-title: true`                     | Suppress the title on the title page                                                                                                                                                       |
+--------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `suppress-short-title: true`               | Suppress the short title in the running header                                                                                                                                             |
+--------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `suppress-author: true`                    | Suppresses the author names below the title. Does not suppress author names in the author note.                                                                                            |
+--------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `suppress-affiliation: true`               | Suppress affiliations below the author names. Does not suppress the affiliation in the correspondence note.                                                                                |
+--------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `suppress-author-note: true`               | Suppress the entire author note                                                                                                                                                            |
+--------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `suppress-orcid: true`                     | Suppress the author ORCID numbers                                                                                                                                                          |
+--------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `suppress-status-change-paragraph: true`   | Suppress the paragraph about status changes (affiliation changes and deceased authors)                                                                                                     |
+--------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `suppress-disclosures-paragraph: true`     | Suppress the paragraph about disclosures (study registration, data sharing, related reports, conflicts of interest, financial support, statements of gratitude, and authorship agreements) |
+--------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `suppress-credit-statement: true`          | Suppress the credit statement                                                                                                                                                              |
+--------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `suppress-corresponding-paragraph: true`   | Suppress the entire correspondence paragraph                                                                                                                                               |
+--------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `suppress-corresponding-group: true`       | Suppress the group in the correspondence address                                                                                                                                           |
+--------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `suppress-corresponding-department: true`  | Suppress the department in the correspondence address                                                                                                                                      |
+--------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `suppress-corresponding-address: true`     | Suppress the street address in the correspondence address                                                                                                                                  |
+--------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `suppress-corresponding-city: true`        | Suppress the city in the correspondence address                                                                                                                                            |
+--------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `suppress-corresponding-region: true`      | Suppress the region/state in the correspondence address                                                                                                                                    |
+--------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `suppress-corresponding-postal-code: true` | Suppress the postal code in the correspondence address                                                                                                                                     |
+--------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `suppress-corresponding-email: true`       | Suppress the email address in the correspondence address                                                                                                                                   |
+--------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `suppress-abstract: true`                  | Suppress the abstract. In the .pdf document, this will also suppress the keywords.                                                                                                         |
+--------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `suppress-impact-statement: true`          | Suppress the impact statement                                                                                                                                                              |
+--------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `suppress-keywords: true`                  | Suppress the keywords below the abstract                                                                                                                                                   |
+--------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `suppress-title-introduction: true`        | Suppress the title in the introduction                                                                                                                                                     |
+--------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: {.primary tbl-colwidths="\[50,50\]"}

# Language Options

You can alter the names of Abstract, Figures, Tables, and References by setting the `lang` field to one of these languages:

| Code | Language   |
|------|------------|
| `en` | English    |
| `zh` | Chinese    |
| `es` | Spanish    |
| `fr` | French     |
| `ja` | Japanese   |
| `de` | German     |
| `pt` | Portuguese |
| `ru` | Russian    |
| `cs` | Czech      |
| `fi` | Finnish    |
| `nl` | Dutch      |
| `it` | Italian    |
| `pl` | Polish     |
| `ko` | Korean     |

: {.primary tbl-colwidths="\[25,75\]"}

However, there are a few options that are specific to apaquarto and thus were not anticipated by Quarto.

+-----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------+
| Field                             | Explanation                                                                                                                                          | Default                                                                                                           |
+===================================+======================================================================================================================================================+===================================================================================================================+
| `citation-last-author-separator`  | APA-style in-text citations with multiple authors are separated by commas with the appropriate translation of the word *and* before the last author. | *and*                                                                                                             |
+-----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------+
| `citation-masked-author`          | The phrase to replace author names in masked citations.                                                                                              | *Masked Citation*                                                                                                 |
+-----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------+
| `citation-masked-date`            | The abbreviated translation for "no date" in masked citations                                                                                        | *n.d.*                                                                                                            |
+-----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------+
| `title-block-author-note`         | The heading of the author note                                                                                                                       | *Author Note*                                                                                                     |
+-----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------+
| `title-block-correspondence-note` | The phrase introducing the correspondence note.                                                                                                      | *Correspondence concerning this article should be addressed to*                                                   |
+-----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------+
| `title-block-role-introduction`   | The phrase introducing the author roles.                                                                                                             | *Author roles were classified using the Contributor Role Taxonomy (CRediT; https://credit.niso.org/) as follows:* |
+-----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------+
| `title-impact-statement`          | The heading for the impact statement                                                                                                                 | *Impact Statement*                                                                                                |
+-----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------+
| `title-word-count`                | The phrase before the word count when `word-count: true`                                                                                             | *Word Count*                                                                                                      |
+-----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------+
| `references-meta-analysis`        | The sentence explaining that citations marked with an asterisk were studies in the meta-analysis.                                                    | *References marked with an asterisk indicate studies included in the meta-analysis.*                              |
+-----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------+

: {.primary tbl-colwidths="\[30,40,30\]"}

All these options must be listed under the `language` field . For example, if we set the `lang` field to `en` (Spanish), the remaining options can also be set:

``` yaml
lang: es
language: 
  citation-last-author-separator: "y"
  citation-masked-author: "Cita Enmascarada"
  citation-masked-title: "Ttulo Enmascarado"
  citation-masked-date: "n.f."
  title-block-author-note: "Nota de Autores"
  title-block-correspondence-note: "La correspondencia relativa a este artculo debe dirigirse a"
  title-block-role-introduction: "Los roles de autor se clasificaron utilizando la taxonoma de roles de colaborador (CRediT; https://credit.niso.org/) de la siguiente manera:"
  references-meta-analysis: "Las referencias marcadas con un asterisco indican estudios incluidos en el metanlisis."
  title-impact-statement: "Declaracin de Impacto"
  title-word-count: "Recuento de Palabras"
```

In addition, many terms that are translated automatically can be overridden. The full list is [here](https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/language/_language.yml). For example, if I wanted "Figure" in figure captions to be "Plot" instead, I would specify the change like so:

``` yaml
language: 
  crossref-fig-title: "Plot"
```

Here are the language terms most likely to be used in apaquarto:

| Field: English Default                 | Explanation           |
|----------------------------------------|-----------------------|
| `section-title-abstract: Abstract`     | Abtract title         |
| `section-title-references: References` | References title      |
| `title-block-keywords: Keywords`       | Keywords              |
| `crossref-fig-title: Figure`           | Figure title prefix   |
| `crossref-tbl-title: Table`            | Table title prefix    |
| `crossref-apx-prefix: Appendix`        | Appendix title prefix |
| `crossref-eq-prefix: Equation`         | Equation title prefix |

: {.primary tbl-colwidths="\[60,40\]"}
