---
title: "Resources"
csl: apa-cv.csl
suppress-bibliography: true
bibliography: bibliography.bib
---

## APA-Style Online

* [APA Style (apa.org)](https://apastyle.apa.org/)
* [APA Style Blog](https://apastyle.apa.org/blog)


## APA-Style Books

* @americanpsychologicalassociationPublicationManualAmerican2020
* @ConciseGuideAPA2020
* @americanpsychologicalassociationMasteringAPAStyle2021

## APA-Style Helper Functions in R

Many packages have helper functions for reporting statistics in and creating tables and figures in APA Style. Here are a few:

* [rempsyc](https://rempsyc.remi-theriault.com/index.html)
* [papaja](https://frederikaust.com/papaja_man/reporting.html)
* [apa](https://github.com/dgromer/apa)
* [apaTables](https://dstanley4.github.io/apaTables/)

## Alternatives to apaquarto

To my knowledge, there is no working quarto extension other than apaquarto that takes a comprehensive approach to APA style with output options in .docx, .html, and .pdf. However, there are other ways to automate the production of APA-style documents. 

### APA style with knitr and $\LaTeX$

The ability to automate APA style via $\LaTeX$ has been around for some time---first via [apa](https://ctan.org/pkg/apa) (APA Style, 5th Edition), then via [apa6](https://ctan.org/pkg/apa6) (APA Style, 6th Edition), and now via [apa7](https://ctan.org/pkg/apa7) (APA Style, 7th Edition). The apaquarto package uses [apa7](https://ctan.org/pkg/apa7) to create .pdf documents. To intermingle R code and $\LaTeX$ code in the same document, R-users could write in an .Rnw file using [sweave or knitr](https://support.posit.co/hc/en-us/articles/200552056-Using-Sweave-and-knitr). I still do so when I need the full flexibility of $\LaTeX$.

### APA style with Rmarkdown and papaja

Unfortunately, most psychology journals require submissions in MS Word (and most collaborators do as well). Learning $\LaTeX$ is fun for some people (e.g., me), but most will not bother. With the arrival of Rmarkdown, it became possible to automate document production with a system that takes just a few minutes to learn. 

The [papaja](https://github.com/crsh/papaja) package by Frederick Aust uses Rmarkdown syntax and does a fantastic job of creating APA-style (6th Edition) documents in .pdf and [gets close to perfect .docx output](https://frederikaust.com/papaja_man/limitations.html#microsoft-word-documents). With a bit of tweaking, [papaja can do most of APA Style (7th Edition)](https://github.com/crsh/papaja/issues/342) for .pdf documents.

### APA style with Quarto and Typst

Matti Vuore is working on an [APA-like quarto extension](https://github.com/mvuorre/quarto-apaish) that uses [Typst](https://typst.app/) instead of $\LaTeX$. As of 2024-02-27, there are aspects of APA style missing, but it looks promising. Because Typst offers many advantages over $\LaTeX$ (e.g., easy reconfiguration and much faster rendering), I would like to adapt apaquarto to use Typst as well. The development of Typst is fast and ongoing, so it will be interesting to see what the future holds.

