---
title: "Template for the APAquarto Format:\n\n7th Edition APA Documents in Quarto"
format:
  apaquarto-docx: default
  native: default
author:
  - name: Sarah Malloc
    affiliations:
      - name: An Organization
        department: The Department
        address: 1 Main St
        city: Boston
        country: USA
        postal-code: 02210-1022
      - A second affilication
    orcid: 0000-0000-0000-0000
    email: sm@example.org
    url: https://example.org/
  - name: Eliza Dealloc
    affiliations:
      - Another Affiliation
abstract: |
  This document is a template demonstrating the apaquarto format.
keywords: [keyword, other keyword]
bibliography: bibliography.bib
---

The include statement
{{< include _extensions/apaquarto/_apa_title.qmd >}}

This is my introductory paragraph. The title will be placed above it automatically. *Do not start with an introductory heading* (e.g., "Introduction"). The title acts as your Level 1 heading for the introduction.

Readers are better able to follow your ideas if you differentiate sections in your introduction with headings. Mostly stick to level 2 headers. Sometimes level 3 heading are needed. Try not to use a level 3 heading Be sparing to the point of stinginess with levels 4 and 5. 

## Level 2 Heading: Flush Left, Bold, Title Case

Subsections of the introduction have level 2 headings. A paragraph after a level 2 Heading is on a new line. Regular paragraphs are indented, flush left, and double-spaced.

You do not need to put text after a heading. You can put higher-level heading directly underneath if you want.

## A Level 2 Heading Without Text Below It

### Level 3 Heading: Flush Left, Bold Italic, Title Case

Subsections of a level 2 heading are placed under level 3 headings.

### Another Level 3 Heading

#### Level 4 Heading: Indented, Flush Left, Bold, Title Case, Ending With a Period.

A paragraph after a level 4 or 5 geading is on a new line in this markdown document but will appear as if it were in the same paragraph .docx format. You need at least one paragraph after a level 4 or 5 heading. If you forget the period at the end of the level 4 or 5 heading, it will be added automatically. A period will not be added if the heading ends with a question mark or an exclamation point.

Subsequent paragraphs go on their own lines.

##### Level 5 Heading: Indented, Flush Left, Bold Italic, Title Case, Ending With a Period

Notice that there was no period after this level 5 heading in the markdown document, but it does appear in the rendered document.

# Method

General remarks on method. This paragraph is optional.

## Participants

Who are they? How were they recruited? Perhaps some basic demographic stats are in order. A table is a great way to avoid repetition in statistical reporting.

## Measures (or Materials or Aparatus)

### Measure A

Describe Measure A.

### Measure B

Describe Measure B.

### Procedure

What did participants do?

### Analysis Plan 

How are the data going to be analyized?

# Results

## Descriptive Statistics

## Add Additional Sections as Needed

# Discussion

Describe results in non-statistical terms. Add sections as needed.

## Limitations and Future Directions

## Conclusion

# References 

<!-- References will auto-populate in the refs div below -->
::: {#refs}
:::

# Appendix 

If there are multiple appendices, label them with level 1 headings as Appendix A, Appendix A, and so forth.
